repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0  # Use the latest stable version
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml

- repo: local
  hooks:
    - id: poetry-pytest-unit
      name: Run pytest unit tests with Poetry
      entry: poetry run pytest -m unit
      language: system
      pass_filenames: false
      always_run: true
      stages: [commit]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.4
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
