version: "3.7"

networks:
  devnet:
    name: ${DOCKER_NETWORK_NAME}
    external: true

services:
  depositor-bot:
    build: .
    networks:
      - devnet
    restart: unless-stopped
    ports:
      - 127.0.0.1:9000:9000
    environment:
      - WEB3_RPC_ENDPOINTS=${WEB3_RPC_ENDPOINTS}
      - LIDO_LOCATOR=${LIDO_LOCATOR}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - CREATE_TRANSACTIONS=${CREATE_TRANSACTIONS}
      - DEPOSIT_CONTRACT=${DEPOSIT_CONTRACT}

      - MESSAGE_TRANSPORTS=${MESSAGE_TRANSPORTS}

      - ONCHAIN_TRANSPORT_ADDRESS=${ONCHAIN_TRANSPORT_ADDRESS}
      - ONCHAIN_TRANSPORT_RPC_ENDPOINTS=${ONCHAIN_TRANSPORT_RPC_ENDPOINTS}

      - RABBIT_MQ_URL=${RABBIT_MQ_URL}
      - RABBIT_MQ_USERNAME=${RABBIT_MQ_USERNAME}
      - RABBIT_MQ_PASSWORD=${RABBIT_MQ_PASSWORD}
      - RELAY_RPC=${RELAY_RPC}
      - AUCTION_BUNDLER_PRIVATE_KEY=${AUCTION_BUNDLER_PRIVATE_KEY}
      - DEPOSIT_MODULES_WHITELIST=${DEPOSIT_MODULES_WHITELIST}
      - PROMETHEUS_PREFIX=${PROMETHEUS_PREFIX}
    command: depositor

  pause-bot:
    build: .
    networks:
      - devnet
    restart: unless-stopped
    ports:
      - 127.0.0.1:9001:9000
    environment:
      - WEB3_RPC_ENDPOINTS=${WEB3_RPC_ENDPOINTS}
      - LIDO_LOCATOR=${LIDO_LOCATOR}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - CREATE_TRANSACTIONS=${CREATE_TRANSACTIONS}
      - DEPOSIT_CONTRACT=${DEPOSIT_CONTRACT}

      - MESSAGE_TRANSPORTS=${MESSAGE_TRANSPORTS}

      - ONCHAIN_TRANSPORT_ADDRESS=${ONCHAIN_TRANSPORT_ADDRESS}
      - ONCHAIN_TRANSPORT_RPC_ENDPOINTS=${ONCHAIN_TRANSPORT_RPC_ENDPOINTS}

      - RABBIT_MQ_URL=${RABBIT_MQ_URL}
      - RABBIT_MQ_USERNAME=${RABBIT_MQ_USERNAME}
      - RABBIT_MQ_PASSWORD=${RABBIT_MQ_PASSWORD}
      - PROMETHEUS_PREFIX=${PROMETHEUS_PREFIX}
    command: pauser

  unvetting-bot:
    build: .
    networks:
      - devnet
    restart: unless-stopped
    ports:
      - 127.0.0.1:9002:9000
    environment:
      - WEB3_RPC_ENDPOINTS=${WEB3_RPC_ENDPOINTS}
      - LIDO_LOCATOR=${LIDO_LOCATOR}
      - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
      - CREATE_TRANSACTIONS=${CREATE_TRANSACTIONS}
      - DEPOSIT_CONTRACT=${DEPOSIT_CONTRACT}

      - MESSAGE_TRANSPORTS=${MESSAGE_TRANSPORTS}

      - ONCHAIN_TRANSPORT_ADDRESS=${ONCHAIN_TRANSPORT_ADDRESS}
      - ONCHAIN_TRANSPORT_RPC_ENDPOINTS=${ONCHAIN_TRANSPORT_RPC_ENDPOINTS}

      - RABBIT_MQ_URL=${RABBIT_MQ_URL}
      - RABBIT_MQ_USERNAME=${RABBIT_MQ_USERNAME}
      - RABBIT_MQ_PASSWORD=${RABBIT_MQ_PASSWORD}

      - PROMETHEUS_PREFIX=${PROMETHEUS_PREFIX}
    command: unvetter
