global:
  scrape_interval: 15s

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['lido-depositor-bot:8080']

remote_write:
  - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
    basic_auth:
      username: 208821
      password: eyJrIjoiZWZmYWVlYWMyZjYwZmI2YTE0MWMyZDZlMjIxY2M0NDZiYTBmOGZiNiIsIm4iOiJuZXcga2V5IiwiaWQiOjU0NDAxNX0=
