NOT_ENOUGH_BALANCE_ON_ACCOUNT = 'Account balance is too low.'
LIDO_CONTRACT_IS_STOPPED = 'Lido contract is stopped.'
LIDO_CONTRACT_HAS_NOT_ENOUGH_BUFFERED_ETHER = 'Lido has less buffered ether than expected.'
LIDO_CONTRACT_HAS_NOT_ENOUGH_SUBMITTED_KEYS = 'No unused keys to deposit.'
GAS_FEE_HIGHER_THAN_RECOMMENDED = 'Gas fee is higher than recommended fee.'
KEY_WAS_USED = 'This key was already used to deposit.'
DEPOSIT_SECURITY_ISSUE = 'Deposit security module prohibits the deposit.'
