name: Integration tests

on:
  push:

jobs:
  tests:
    name: App tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Setup poetry
        run: |
          curl -sSL https://install.python-poetry.org/ | python - && echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        env:
          POETRY_VERSION: 1.8.2

      - name: Install dependencies
        run: |
          poetry install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Integration tests with pytest
        if: success() || failure()
        run: |
          poetry run pytest tests -m integration -v -s --log-cli-level=INFO --tb=short
        env:
          WEB3_RPC_ENDPOINTS: ${{ secrets.WEB3_RPC_ENDPOINT }}
          TESTNET_WEB3_RPC_ENDPOINTS: 'https://ethereum-holesky-rpc.publicnode.com'
          DEPOSIT_CONTRACT: "0x00000000219ab540356cBB839Cbe05303d7705Fa"
          LIDO_LOCATOR: "0xe2EF9536DAAAEBFf5b1c130957AB3E80056b06D8"
          ONCHAIN_TRANSPORT_RPC_ENDPOINTS: "https://rpc.gnosis.gateway.fm"
          ONCHAIN_TRANSPORT_ADDRESS: "0x37De961D6bb5865867aDd416be07189D2Dd960e6"
          DEPOSIT_MODULES_WHITELIST: "1,2,3,4,5"
          ANVIL_PATH: ""
